version: "2.1"
services:
  liveflow:
    image: liveflow_custom:latest
    mem_limit: 350m
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - "~/.store:/app/videos"
    ports:
      - "8044:8044"
      - "1930:1930"
      - "40000-40010:40000-40010/udp"
    environment:
      DOCKER_MODE: "true"
    build:
      context: ./
      dockerfile: Dockerfile
